///////////////////////////////////////////////////////////////////////////////
// TrackRtStartTimeClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TrackRtStartTimeClassFactory.h"
#include "TrackRtStartTimeServices.h"
#include "TrackRtStartTimeVersion.h"
#include "RtStartTimeModule.h"

BEGIN_CLASS_MAP(CTrackRtStartTimeClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_TrackRtStartTime, CID_TrackRtStartTimeCRtStartTimeModule, SRVNAME_TRACKRTSTARTTIME "!CRtStartTimeModule", CRtStartTimeModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTrackRtStartTimeClassFactory::CTrackRtStartTimeClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_TRACKRTSTARTTIME));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(TrackRtStartTime));
#endif //defined(TCDBG_UNIT_VERSION)
}

