///////////////////////////////////////////////////////////////////////////////
// TrackRtStartTimeServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TrackRtStartTime = 0x3F000000;
#define SRVNAME_TRACKRTSTARTTIME "TrackRtStartTime"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TrackRtStartTimeCRtStartTimeModule = {0x3ef156bc,0x4f0b,0x471e,{0x9b,0x99,0x2c,0xac,0xfa,0xb2,0x69,0x95}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _RtStartTimeModuleOutputs
{
	ULONGLONG RtStartTime;
} RtStartTimeModuleOutputs, *PRtStartTimeModuleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_RtStartTimeModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
